In [15]:
import tensorflow as tf
import numpy as np

In [2]:
dataset = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6,7])

In [3]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [4]:
for ele in dataset:
    print(ele)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)


In [6]:
for ele in dataset:
    print(ele.numpy())

1
2
3
4
5
6
7


In [7]:
dataset = tf.data.Dataset.from_tensor_slices([[1,2],[3,4],[5,6]])

In [8]:
dataset

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [9]:
for ele in dataset:
    print(ele.numpy())

[1 2]
[3 4]
[5 6]


In [10]:
dataset_dic = tf.data.Dataset.from_tensor_slices({'a':[1,2,3,4],'b':[5,6,7,8]})

In [13]:
for ele in dataset_dic:
    print(ele)

{'a': <tf.Tensor: id=82, shape=(), dtype=int32, numpy=1>, 'b': <tf.Tensor: id=83, shape=(), dtype=int32, numpy=5>}
{'a': <tf.Tensor: id=86, shape=(), dtype=int32, numpy=2>, 'b': <tf.Tensor: id=87, shape=(), dtype=int32, numpy=6>}
{'a': <tf.Tensor: id=90, shape=(), dtype=int32, numpy=3>, 'b': <tf.Tensor: id=91, shape=(), dtype=int32, numpy=7>}
{'a': <tf.Tensor: id=94, shape=(), dtype=int32, numpy=4>, 'b': <tf.Tensor: id=95, shape=(), dtype=int32, numpy=8>}


In [16]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1,2,3,4,5,6,7]))

In [17]:
for ele in dataset.take(4):
    print(ele.numpy())

1
2
3
4


In [19]:
next(iter(dataset.take(1)))

<tf.Tensor: id=128, shape=(), dtype=int32, numpy=1>

In [24]:
dataset = dataset.shuffle(7)
dataset = dataset.repeat(count=3)
dataset = dataset.batch(3)

In [25]:
for ele in dataset:
    print(ele.numpy())

[2 3 5]
[1 2 6]
[7 4 6]
[5 4 3]
[5 2 3]
[1 1 4]
[6 7 7]
[1 6 2]
[3 5 6]
[7 1 4]
[3 5 4]
[5 6 2]
[7 2 3]
[4 7 1]
[3 2 7]
[1 5 2]
[6 5 3]
[3 6 7]
[4 5 2]
[4 1 1]
[4 7 6]


In [26]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1,2,3,4,5,6,7]))

In [27]:
dataset = dataset.map(tf.square)

In [28]:
for ele in dataset:
    print(ele.numpy())

1
4
9
16
25
36
49
