In [18]:
import tensorflow as tf
import numpy as np

In [2]:
tf.executing_eagerly()

True

In [4]:
print(tf.test.is_gpu_available())

True


In [5]:
x = [[2,]]

In [6]:
m = tf.matmul(x,x)

In [7]:
print(m)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [8]:
m.numpy()

array([[4]])

In [9]:
a = tf.constant([[1,2],[3,4]])

In [10]:
a

<tf.Tensor: id=3, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [11]:
b = tf.add(a,1)
b

<tf.Tensor: id=5, shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [14]:
c = tf.multiply(a,b)
c

<tf.Tensor: id=7, shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]])>

In [15]:
num = tf.convert_to_tensor(10)
num

<tf.Tensor: id=8, shape=(), dtype=int32, numpy=10>

In [17]:
for i in range(num.numpy()):
    i = tf.constant(i)
    if int(i%2) == 0:
        print('even')
    else:
        print('odd')

even
odd
even
odd
even
odd
even
odd
even
odd


In [19]:
d = np.array([[5,6],[7,8]])

In [20]:
(a+d).numpy()

array([[ 6,  8],
       [10, 12]])

In [21]:
g = tf.convert_to_tensor(10)
g

<tf.Tensor: id=41, shape=(), dtype=int32, numpy=10>

In [22]:
float(g)

10.0